// <auto-generated />
using Home.Db.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Home.Db.Migrations
{
    [DbContext(typeof(HomeDbContext))]
    [Migration("20251026203603_StateColumns")]
    partial class StateColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Home.Db.Model.Device", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("AllowStateChange")
                        .HasColumnType("INTEGER")
                        .HasColumnName("allow_switch_state");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("device_type");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("friendly_name")
                        .UseCollation("NOCASE");

                    b.Property<string>("IeeeAddress")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("ieee_address")
                        .UseCollation("NOCASE");

                    b.Property<string>("PowerOnBehavior")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("power_on_behavior");

                    b.HasKey("Id");

                    b.HasIndex("FriendlyName")
                        .IsUnique();

                    b.HasIndex("IeeeAddress")
                        .IsUnique();

                    b.ToTable("device");
                });
#pragma warning restore 612, 618
        }
    }
}
